server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: TRUE
      force: TRUE

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jackson:
    serialization:
      fail-on-empty-beans: FALSE
    
  jpa:
    open-in-view: TRUE
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: FALSE

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/base?serverTimezone=Asia/Seoul
    username: mae
    password: mae1234

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
